// UGC Tags for community posts
export const ugcTags = [
  { name: 'reformer', slug: 'reformer' },
  { name: 'mat', slug: 'mat' },
  { name: 'progress', slug: 'progress' },
  { name: 'home studio', slug: 'home-studio' },
  { name: 'studio visit', slug: 'studio-visit' },
  { name: 'morning routine', slug: 'morning-routine' },
  { name: 'beginner', slug: 'beginner' },
  { name: 'advanced', slug: 'advanced' },
  { name: 'flexibility', slug: 'flexibility' },
  { name: 'strength', slug: 'strength' },
];

// Sample UGC posts for demonstration
// Note: Uses placeholder images - replace with real images in production
export const ugcSamplePosts = [
  {
    caption: 'Morning reformer session complete! Starting the day with core work sets the tone for everything. 💪',
    mediaUrl: '/uploads/ugc/sample/reformer-morning.jpg',
    mediaType: 'image',
    aspectRatio: 1.0,
    fileSizeBytes: 245000,
    status: 'approved',
    isFeatured: true,
    featuredAt: new Date(),
    likesCount: 24,
    commentsCount: 5,
    savesCount: 8,
    tagSlugs: ['reformer', 'morning-routine', 'strength'],
  },
  {
    caption: 'Finally nailed the teaser after weeks of practice. Consistency is everything in Pilates.',
    mediaUrl: '/uploads/ugc/sample/mat-teaser.jpg',
    mediaType: 'image',
    aspectRatio: 0.8,
    fileSizeBytes: 189000,
    status: 'approved',
    isFeatured: false,
    likesCount: 18,
    commentsCount: 3,
    savesCount: 5,
    tagSlugs: ['mat', 'progress', 'advanced'],
  },
  {
    caption: 'My little corner of calm. Home studio finally set up! 🏠',
    mediaUrl: '/uploads/ugc/sample/home-studio.jpg',
    mediaType: 'image',
    aspectRatio: 1.33,
    fileSizeBytes: 312000,
    status: 'approved',
    isFeatured: true,
    featuredAt: new Date(),
    likesCount: 42,
    commentsCount: 12,
    savesCount: 15,
    tagSlugs: ['home-studio', 'reformer'],
  },
  {
    caption: 'Week 4 of the beginner program. Already feeling stronger!',
    mediaUrl: '/uploads/ugc/sample/progress-week4.jpg',
    mediaType: 'image',
    aspectRatio: 1.0,
    fileSizeBytes: 198000,
    status: 'approved',
    isFeatured: false,
    likesCount: 15,
    commentsCount: 8,
    savesCount: 3,
    tagSlugs: ['progress', 'beginner', 'mat'],
  },
  {
    caption: 'Beautiful space at @pilatesstudio - highly recommend!',
    mediaUrl: '/uploads/ugc/sample/studio-visit.jpg',
    mediaType: 'image',
    aspectRatio: 1.5,
    fileSizeBytes: 278000,
    status: 'pending',
    isFeatured: false,
    likesCount: 0,
    commentsCount: 0,
    savesCount: 0,
    tagSlugs: ['studio-visit', 'reformer'],
  },
  {
    caption: 'Flexibility journey - side splits getting closer!',
    mediaUrl: '/uploads/ugc/sample/flexibility.jpg',
    mediaType: 'image',
    aspectRatio: 0.75,
    fileSizeBytes: 167000,
    status: 'pending',
    isFeatured: false,
    likesCount: 0,
    commentsCount: 0,
    savesCount: 0,
    tagSlugs: ['flexibility', 'progress'],
  },
];
